from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from importlib.util import find_spec
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
_EMBEDDED_LOCAL = _ROOT / "config" / "embedded_local.py"
_ENV_CLOUDFLARE_TUNNEL_TOKEN = "STREAM_CHEREMSHA_CLOUDFLARE_TUNNEL_TOKEN"
_ENV_CLOUDFLARE_TUNNEL_HOSTNAME = "STREAM_CHEREMSHA_CLOUDFLARE_TUNNEL_HOSTNAME"
_ENV_KICK_CLIENT_ID = "STREAM_CHEREMSHA_KICK_CLIENT_ID"
_ENV_KICK_CLIENT_SECRET = "STREAM_CHEREMSHA_KICK_CLIENT_SECRET"
_ENV_OVERLAY_CERTIFICATE = "STREAM_CHEREMSHA_OVERLAY_CERTIFICATE"
_ENV_OVERLAY_PRIVATE_KEY = "STREAM_CHEREMSHA_OVERLAY_PRIVATE_KEY"
_ENV_OVERLAY_PUBLIC_HOSTNAME = "STREAM_CHEREMSHA_OVERLAY_PUBLIC_HOSTNAME"


def _write_embedded_local(
    *, overlay_cert_path: str = "", overlay_key_path: str = ""
) -> bool:
    """Materialize build-time secrets for Nuitka to compile into the binary."""
    token = (os.environ.get(_ENV_CLOUDFLARE_TUNNEL_TOKEN) or "").strip()
    hostname = (os.environ.get(_ENV_CLOUDFLARE_TUNNEL_HOSTNAME) or "").strip()
    kick_cid = (os.environ.get(_ENV_KICK_CLIENT_ID) or "").strip()
    kick_sec = (os.environ.get(_ENV_KICK_CLIENT_SECRET) or "").strip()
    certificate = (os.environ.get(_ENV_OVERLAY_CERTIFICATE) or "").strip()
    private_key = (os.environ.get(_ENV_OVERLAY_PRIVATE_KEY) or "").strip()
    public_hostname = (
        os.environ.get(_ENV_OVERLAY_PUBLIC_HOSTNAME) or "app.cheremsha.click"
    ).strip()
    if overlay_cert_path or overlay_key_path:
        if not overlay_cert_path or not overlay_key_path:
            raise SystemExit("Both --overlay-cert and --overlay-key are required")
        try:
            certificate = Path(overlay_cert_path).read_text(encoding="utf-8").strip()
            private_key = Path(overlay_key_path).read_text(encoding="utf-8").strip()
        except OSError as e:
            raise SystemExit(f"Unable to read overlay TLS files: {e}") from e
    if bool(certificate) != bool(private_key):
        raise SystemExit(
            f"Both {_ENV_OVERLAY_CERTIFICATE} and {_ENV_OVERLAY_PRIVATE_KEY} are required"
        )
    if not any((token, hostname, kick_cid, kick_sec, certificate, private_key)):
        if _EMBEDDED_LOCAL.is_file():
            _EMBEDDED_LOCAL.unlink()
        return False
    _EMBEDDED_LOCAL.write_text(
        "# Auto-generated by cheremsha-build. Do not edit.\n"
        f"CLOUDFLARE_TUNNEL_TOKEN = {token!r}\n"
        f"CLOUDFLARE_TUNNEL_HOSTNAME = {hostname!r}\n"
        f"KICK_CLIENT_ID = {kick_cid!r}\n"
        f"KICK_CLIENT_SECRET = {kick_sec!r}\n"
        f"OVERLAY_CERTIFICATE = {certificate!r}\n"
        f"OVERLAY_PRIVATE_KEY = {private_key!r}\n"
        f"OVERLAY_PUBLIC_HOSTNAME = {public_hostname!r}\n",
        encoding="utf-8",
    )
    return True


def _remove_embedded_local(written: bool) -> None:
    if written and _EMBEDDED_LOCAL.is_file():
        _EMBEDDED_LOCAL.unlink()


def _run(cmd: list[str]) -> None:
    proc = subprocess.run(cmd, check=False)
    if proc.returncode != 0:
        raise SystemExit(proc.returncode)


def _remove_stale_nuitka_build_workdirs(out_dir: Path) -> None:
    """
    After a killed/interrupted Nuitka run, *.build can contain half-written *.c files.
    Nuitka then asserts the output path is absent and crashes (e.g. module.PySide6.c).
    """
    if not out_dir.is_dir():
        return
    for child in out_dir.iterdir():
        if child.is_dir() and child.suffix == ".build":
            shutil.rmtree(child, ignore_errors=False)


def _require_supported_nuitka() -> None:
    try:
        import nuitka  # noqa: F401  # type: ignore[import-not-found]
    except ImportError as e:
        raise SystemExit(
            'Nuitka is not installed. Install with: pip install -e ".[build]"',
        ) from e

    # NOTE: Nuitka behavior can vary by version. If builds regress, pin a known-good
    # version in your environment (e.g. via `pip install nuitka==...`).


def _nuitka_cmd(
    *,
    out_dir: Path,
    onefile: bool,
    debug: bool,
    show_console: bool,
    jobs: str,
    exclude_tiktok_proto: bool,
    low_memory: bool,
    clang: bool,
    mingw64: bool,
    msvc: str | None,
) -> list[str]:
    _require_supported_nuitka()

    qml_dir = _ROOT / "qml"
    assets_dir = _ROOT / "assets"
    icon_png = assets_dir / "icon.png"
    icon_ico_src = assets_dir / "icon.ico"
    icon_ico_gen = out_dir / "icon.ico"

    def _resolve_windows_icon_ico() -> Path | None:
        if not sys.platform.startswith("win"):
            return None
        if icon_ico_src.is_file():
            return icon_ico_src
        if not icon_png.is_file():
            return None
        try:
            from PIL import Image  # type: ignore[import-not-found]
        except ImportError as e:
            raise SystemExit(
                "Windows icon: missing assets/icon.ico and Pillow is not installed. "
                "Either add stream_cheremsha/assets/icon.ico or install build extras: "
                'pip install -e ".[build]"',
            ) from e
        img = Image.open(icon_png)
        # Common Windows icon sizes; Pillow will downscale as needed.
        sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
        img.save(icon_ico_gen, format="ICO", sizes=sizes)
        return icon_ico_gen

    def _has_pkg(name: str) -> bool:
        return find_spec(name) is not None

    cmd = [
        sys.executable,
        "-m",
        "nuitka",
        "--standalone",
        "--follow-imports",
        # NOTE: Avoid `--experimental=ignore-extra-micro-pass` here: it can *cause*
        # an AssertionError (`assert micro_passes == 0`) on some dependency graphs.
        # Prevent external site-packages at runtime (can cause duplicate torch extensions).
        "--python-flag=isolated",
        "--python-flag=safe_path",
        # PyTorch compiler stack is not required for inference; can crash Nuitka optimization.
        # Exclude it from compilation to keep builds stable.
        "--nofollow-import-to=torch._dynamo",
        "--nofollow-import-to=torch._inductor",
        "--nofollow-import-to=torch._functorch",
        "--nofollow-import-to=torch._export",
        # Nuitka may pull in Cython (build-time tooling) via transitive deps.
        # It is not needed at runtime.
        "--nofollow-import-to=Cython",
        # Nuitka 4.0.8 can crash optimizing librosa on some graphs; keep it as bytecode.
        "--nofollow-import-to=librosa",
        # yt-dlp: one auto-generated module (`lazy_extractors`) is enormous; compiling it
        # to C can hit MSVC fatal error C1002 (compiler out of heap) on GitHub runners.
        # Do not compile it; runtime still loads it as Python bytecode in the dist.
        "--nofollow-import-to=yt_dlp.extractor.lazy_extractors",
        # Do NOT `--nofollow-import-to=TikTokLive`: Nuitka treats that as the whole package
        # *tree* (submodules are "below namespace"), which blocks `--include-package` scans
        # and triggers "Did not follow import to unused 'TikTokLive'". TikTok chat needs the
        # package included normally. If MSVC C1002 appears on a specific submodule, add a
        # narrow nofollow (e.g. one file), not the top-level package name.
        # If you hit MSVC C1002 elsewhere, try `--low-memory --jobs 1`.
        # `--exclude-tiktok-proto` skips TikTokLive.proto (breaks TikTok chat); last resort only.
        # Some stacks do not need distributed/RPC, but it can crash in standalone builds
        # with duplicate type registration (e.g. RpcBackendOptions already defined).
        "--nofollow-import-to=torch.distributed",
        "--include-package=TikTokLive",
        # OBS actions use obsws-python (obsws_python); it pulls websocket-client as `websocket`.
        # These are imported from UI callbacks and can be missed by module graph heuristics.
        "--include-package=obsws_python",
        "--include-package=websocket",
        "--enable-plugin=pyside6",
        # Needed for QQuickWidget/QML and QMediaPlayer backends in standalone builds.
        "--include-qt-plugins=qml,multimedia",
        "--module-parameter=torch-disable-jit=yes",
        f"--output-dir={out_dir}",
        "--assume-yes-for-downloads",
        # Keep data files under the package path so runtime code can
        # locate them relative to `stream_cheremsha/...`.
        f"--include-data-dir={qml_dir}=stream_cheremsha/qml",
        f"--include-data-dir={assets_dir}=stream_cheremsha/assets",
    ]

    # Ensure TLS works in standalone builds (httpx/ssl need a CA bundle).
    # Certifi ships `cacert.pem` as a data file; make sure it's included.
    if _has_pkg("certifi"):
        import certifi  # type: ignore[import-not-found]

        cacert = Path(certifi.where()).resolve()
        if cacert.is_file():
            cmd.append("--include-package=certifi")
            cmd.append(f"--include-data-file={cacert}=certifi/cacert.pem")

    for pkg in (
        "googleapiclient",
        "google_auth_httplib2",
        "httplib2",
        "google.auth",
        "requests",
        "curl_cffi",
        "chat_downloader",
        "uritemplate",
    ):
        if _has_pkg(pkg):
            cmd.append(f"--include-package={pkg}")

    if clang:
        cmd.append("--clang")
    if mingw64:
        cmd.append("--mingw64")
    if msvc:
        cmd.append(f"--msvc={msvc}")

    if low_memory:
        cmd.append("--low-memory")

    if exclude_tiktok_proto:
        # Explicitly exclude TikTok protobuf modules (TikTokLive features will break).
        cmd.append("--nofollow-import-to=TikTokLive.proto")

    if jobs:
        cmd.append(f"--jobs={jobs}")
    if onefile:
        cmd.append("--onefile")
    if debug:
        cmd.append("--debug")
    if sys.platform.startswith("win"):
        # Our app is GUI-first; show a console only when requested (helps debugging).
        if not show_console:
            cmd.append("--windows-console-mode=disable")
        # Name the resulting executable after the app, not the entrypoint filename.
        cmd.append("--output-filename=cheremsha.exe")
        ico = _resolve_windows_icon_ico()
        if ico is not None and ico.is_file():
            cmd.append(f"--windows-icon-from-ico={ico}")
        # Do not request admin privileges for the built binary.
    else:
        cmd.append("--output-filename=cheremsha")

    # Entry point (same as `cheremsha`)
    cmd.append(str((_ROOT / "app" / "main.py").resolve()))
    return cmd


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(
        prog="cheremsha-build",
        description="Build standalone binary via Nuitka.",
    )
    p.add_argument(
        "--out",
        default="dist/nuitka",
        help="Output directory (default: dist/nuitka)",
    )
    p.add_argument(
        "--onefile",
        action="store_true",
        help="Build a single-file executable (slower start).",
    )
    p.add_argument(
        "--fast",
        action="store_true",
        help="Fast build (default): no debug, no onefile.",
    )
    p.add_argument("--debug", action="store_true", help="Enable Nuitka debug build (slower).")
    p.add_argument(
        "--jobs",
        default=str(os.cpu_count() or 4),
        help="Nuitka jobs (integer). Default: CPU count.",
    )
    p.add_argument(
        "--console",
        action="store_true",
        help="Show a console window / console output (useful for debugging).",
    )
    p.add_argument(
        "--exclude-tiktok-proto",
        action="store_true",
        help="Exclude TikTokLive protobuf modules (will break TikTokLive at runtime).",
    )
    p.add_argument(
        "--low-memory",
        action="store_true",
        help="Ask Nuitka to use less memory (slower; implies jobs=1 behavior).",
    )
    p.add_argument(
        "--clang",
        action="store_true",
        help="Build with Clang (Nuitka: --clang).",
    )
    p.add_argument(
        "--mingw64",
        action="store_true",
        help="Build with MinGW64 (Nuitka: --mingw64).",
    )
    p.add_argument(
        "--msvc",
        default=None,
        help="Build with a specific MSVC version, e.g. 14.3 (Nuitka: --msvc=...).",
    )
    p.add_argument(
        "--clean",
        action="store_true",
        help=(
            "Remove Nuitka *.build workdirs under --out before compiling. "
            "Use after a killed build if Nuitka crashes with "
            "AssertionError: ... module.*.c already exists."
        ),
    )
    p.add_argument(
        "--overlay-cert",
        default="",
        help="PEM certificate/full chain to embed for the widgets HTTPS server.",
    )
    p.add_argument(
        "--overlay-key",
        default="",
        help="PEM private key to embed for the widgets HTTPS server.",
    )
    ns = p.parse_args(argv)

    if ns.fast:
        ns.debug = False
        ns.onefile = False

    out = Path(ns.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    if ns.clean:
        _remove_stale_nuitka_build_workdirs(out)
    embedded_written = _write_embedded_local(
        overlay_cert_path=str(ns.overlay_cert), overlay_key_path=str(ns.overlay_key)
    )
    cmd = _nuitka_cmd(
        out_dir=out,
        onefile=ns.onefile,
        debug=ns.debug,
        show_console=ns.console,
        jobs=str(ns.jobs),
        exclude_tiktok_proto=bool(ns.exclude_tiktok_proto),
        low_memory=bool(ns.low_memory),
        clang=bool(ns.clang),
        mingw64=bool(ns.mingw64),
        msvc=str(ns.msvc) if ns.msvc else None,
    )
    try:
        _run(cmd)
    finally:
        _remove_embedded_local(embedded_written)


if __name__ == "__main__":
    main()
