"""Shared Qt stylesheets for Cheremsha UI surfaces."""

from __future__ import annotations


def settings_panel_stylesheet() -> str:
    """Dark settings-panel chrome (group boxes, inputs, buttons, scrollbars).

    Used by the main settings tab and modal settings dialogs so they share the
    same visual language.
    """
    return (
        "QWidget { background-color: transparent; color: #e6e6e6; }"
        "QDialog#pointsSettingsDialog { "
        "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
        "stop:0 #0f172a, stop:0.55 #0b1220, stop:1 #070910); }"
        "QGroupBox { border: 1px solid #2a3142; border-radius: 12px; margin-top: 16px; "
        "padding-top: 10px; padding-bottom: 12px; padding-left: 14px; padding-right: 14px; "
        "font-weight: 600; background-color: rgba(18, 22, 32, 210); }"
        "QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; "
        "left: 12px; padding: 1px 8px; color: #e8eaed; font-size: 12px; "
        "background: rgba(8, 10, 14, 170); border-radius: 8px; }"
        "QScrollArea { border: none; background: transparent; }"
        "QScrollBar:vertical { width: 10px; background: #0f1219; margin: 4px 2px 4px 0; "
        "border-radius: 5px; border: 1px solid #1e2430; }"
        "QScrollBar::handle:vertical { background: #3d4a60; min-height: 32px; "
        "border-radius: 5px; margin: 2px; }"
        "QScrollBar::handle:vertical:hover { background: #52607a; }"
        "QScrollBar::handle:vertical:pressed { background: #0d9488; }"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; "
        "border: none; }"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { "
        "background: transparent; }"
        "QLabel { color: #d7deea; }"
        "QLabel#mutedHint { color: #8b95a5; font-size: 11px; }"
        "QLabel#formFieldLabel { color: #d7deea; }"
        "QLineEdit, QComboBox, QSpinBox {"
        " background: #10141c; color: #e6e6e6; border: 1px solid #2a3142; "
        "border-radius: 10px; padding: 7px 10px; min-height: 36px; }"
        "QSpinBox { padding-right: 28px; }"
        "QSpinBox::up-button, QSpinBox::down-button {"
        " subcontrol-origin: border; width: 24px; border-left: 1px solid #2a3142; "
        "background: #1a2130; }"
        "QSpinBox::up-button { subcontrol-position: top right; border-top-right-radius: 9px; }"
        "QSpinBox::down-button { subcontrol-position: bottom right; "
        "border-bottom-right-radius: 9px; }"
        "QSpinBox::up-button:hover, QSpinBox::down-button:hover { background: #202a3a; }"
        "QSpinBox::up-button:pressed, QSpinBox::down-button:pressed { background: #2a3446; }"
        "QSpinBox::up-arrow {"
        " width: 0; height: 0; border-left: 4px solid transparent; "
        "border-right: 4px solid transparent; border-bottom: 5px solid #9aa5b8; }"
        "QSpinBox::down-arrow {"
        " width: 0; height: 0; border-left: 4px solid transparent; "
        "border-right: 4px solid transparent; border-top: 5px solid #9aa5b8; }"
        "QPushButton { background-color: #1a2130; color: #e6e6e6; "
        "border: 1px solid #2f3a4d; border-radius: 8px; padding: 8px 14px; min-height: 36px; }"
        "QPushButton:hover { background-color: #202a3a; border-color: #3b4458; }"
        "QPushButton:pressed { background-color: #2a3446; border-color: #4a5568; }"
        "QPushButton:focus { outline: none; }"
        "QPushButton#primaryButton {"
        " background-color: #0f766e; border: 1px solid #2dd4bf; color: #ecfdf5; }"
        "QPushButton#primaryButton:hover {"
        " background-color: #14b8a6; border-color: #5eead4; }"
        "QPushButton#primaryButton:pressed {"
        " background-color: #0d9488; border-color: #2dd4bf; }"
    )
